use super::*;

use hex::FromHex;

////////////////////////////////////////////////////////////
// Ntor tests                                             //
////////////////////////////////////////////////////////////

#[test]
#[cfg(feature = "elligator2")]
fn repres_from_pubkey_kleshni() {
    // testcases from kleshni
    for (i, testcase) in encoding_testcases().iter().enumerate() {
        let point = <[u8; 32]>::from_hex(testcase.point).expect("failed to decode hex point");

        let edw_point = MontgomeryPoint(point)
            .to_edwards(testcase.high_y as u8)
            .expect("failed to convert point to edwards");
        let v_in_sqrt = v_in_sqrt_pubkey_edwards(&edw_point);

        let repres: Option<[u8; 32]> =
            point_to_representative(&MontgomeryPoint(point), v_in_sqrt.into()).into();
        if testcase.representative.is_some() {
            assert_eq!(
                testcase.representative.expect("checked, is some"),
                hex::encode(repres.expect("failed to get representative from point")),
                "[good case] kleshni ({i}) bad pubkey from true representative"
            );
        } else {
            assert!(
                repres.is_none(),
                "[good case] kleshni ({i}) expected none got repres {}",
                hex::encode(repres.expect("this should not fail"))
            );
        }
    }
}

#[test]
#[cfg(feature = "elligator2")]
/// Ensure private keys generate the expected representatives. These tests
/// are generated from agl/ed25519 to ensure compatibility.
fn repres_from_privkey_agl() {
    for (i, vector) in ntor_valid_test_vectors().iter().enumerate() {
        let privkey = <[u8; 32]>::from_hex(vector[0]).expect("failed to decode hex privatekey");
        let true_repres = vector[3];

        let pubkey_clean = EdwardsPoint::mul_base_clamped(privkey)
            .to_montgomery()
            .to_bytes();
        assert_eq!(
            hex::encode(pubkey_clean),
            vector[1],
            "[good case] agl/ed25519 ({i}) incorrect clean pubkey from privkey"
        );

        let pubkey = EdwardsPoint::mul_base_clamped_dirty(privkey);
        assert_eq!(
            hex::encode(pubkey.to_montgomery().to_bytes()),
            vector[2],
            "[good case] agl/ed25519 ({i}) incorrect pubkey from privkey"
        );

        let r1 = representative_from_privkey(&privkey, 0u8)
            .expect("[good case] agl/ed25519 ({i}) failed to get representative from privkey");

        let repres = representative_from_pubkey(&pubkey, 0u8)
            .expect("[good case] agl/ed25519 ({i}) failed to get representative from pubkey");

        assert_eq!(hex::encode(r1), hex::encode(repres));
        assert_eq!(
            true_repres,
            hex::encode(repres),
            "[good case] agl/ed25519 ({i}) incorrect representative from privkey"
        );
    }
}

#[test]
#[cfg(feature = "elligator2")]
fn pubkey_from_repres() {
    // testcases from kleshni
    for (i, testcase) in decoding_testcases().iter().enumerate() {
        let repres = <[u8; 32]>::from_hex(testcase.representative)
            .expect("failed to decode hex representative");

        let point = MontgomeryPoint::map_to_point(&repres);
        assert_eq!(
            testcase.point,
            hex::encode(point.to_bytes()),
            "[good case] kleshni ({i}) bad representative from point"
        );

        let point_from_unbounded = MontgomeryPoint::map_to_point_unbounded(&repres);
        assert_eq!(
            testcase.non_lsr_point,
            hex::encode(point_from_unbounded.to_bytes()),
            "[good case] kleshni ({i}) bad representative from point"
        );
    }

    // testcases from golang agl/ed25519
    for (i, vector) in ntor_valid_test_vectors().iter().enumerate() {
        let true_pubkey = vector[2];
        let repres = <[u8; 32]>::from_hex(vector[3]).expect("failed to decode hex representative");

        // ensure that the representative can be reversed to recover the
        // original public key.
        let pubkey = MontgomeryPoint::map_to_point(&repres);
        assert_eq!(
            true_pubkey,
            hex::encode(pubkey.to_bytes()),
            "[good case] agl/ed25519 ({i}) bad pubkey from true representative"
        );
    }
}

#[test]
#[cfg(feature = "elligator2")]
fn non_representable_points() {
    for (i, key) in ntor_invalid_keys().iter().enumerate() {
        let privkey = <[u8; 32]>::from_hex(key).expect("failed to decode hex privkey");

        // ensure that the representative can be reversed to recover the
        // original public key.
        let res: Option<[u8; 32]> = representative_from_privkey(&privkey, 0u8);
        assert!(
            res.is_none(),
            "[bad case] agl/ed25519 ({i}) expected None, got Some({})",
            hex::encode(res.expect("this shouldn't happen"))
        );
    }
}

/// returns a set of keypair encodings generated by (a fork of) the golang
/// implementation agl/ed25519 which is used by the mainstream obfs4
/// library. Each set of three strings is
///
///   1) the generated private key scalar
///   2) the associated public key point when using normal mul_base_clamped
///   2) the associated public key point w/ cofactor creates using mul_base_clamped_dirty
///   3) the successfully created representative from the dirty publicKey
///
/// All of these are valid keypairs and our public key to
/// representative implementation (and repres-to-pubkey) should match and
/// handle these cases.
///
fn ntor_valid_test_vectors() -> [[&'static str; 4]; 21] {
    [
        [
            "b531f4243aa4a013f0f87a2eaaec47807844a2f375d40b774e824d37a196b2b6",
            "aa2d8f1c47f717d96edbf503ff0d9fa782849c486ad8a7c15b2bf4a793902c35",
            "04a47c7903661acf03cd71e5400c8b96650bb3620d2ae91b674713ca5f2ac673",
            "f30130eb1c192cda48a503932c8751232fd784ab7792acba499807e78084a909",
        ],
        [
            "d63f245d00c57683e8f3f7174b2601aa89319d39823e42aa388fb4f349b8df16",
            "97ed90e92c02c5a488d4d9589174867d0d640c460caf4c61833f6c6cb5f5f874",
            "3741b60e375affc17d0dba931bb0f5f4540c31c67a979c3399596103283dd27d",
            "3a50a823f482a7af1ac898446850dd643b9a68b530df4cebe7d9f108ebe8933b",
        ],
        [
            "2b6b4888ec2d23748f708627c1a9260b0f10dd2fbc941e44cd578d69760d9873",
            "79a9d72800606a520b580bdba40882fa78f13f61a4a402ef615cf01ef5875450",
            "d8db37c0fafe81757adcf4f580daff6f68b200a4a38965a4a71ced905e67ee26",
            "ed3b270440c2c9d6630bd2b92fd07ede4b8ac3881a286bc9d5f225e35e1d5a31",
        ],
        [
            "9228b2e3a95462b6d9f32cc326c3c55107972e9cb426301d33861bec15049b65",
            "995ac596a4c4f6da1a7ae3cc5ef9dcfb74443717a68dc03972882c9ba7db1823",
            "9d8ef0820c3ed0b0c7d29e178eaf31431ca4ee1e97cdab08ea6c85946a3e5e6b",
            "b918077e9e1283c0cc44055a28b97ea131e8517983ed033d60e99b818f55fe00",
        ],
        [
            "21af4b82c709c6dbf0a1aa28b7a045ea6a20448ec36c9f5f6eadf60c9a71ee66",
            "f8ac0dd56d7c9f7d681a8fec38675a39e37e2b9780995ce6cdc1f4da25356860",
            "41b49d99d7490aae2c774893d2f24147c353f4179ef318c1954899eb93ba7316",
            "e1d2992fce97a72d40483f940aa1156d34eea4e5789336155d718f0d74eb9e27",
        ],
        [
            "465fd0ac29e17ecadf922676a99a40e59ef20ed7d964663fce6d09cfe247599e",
            "5246cdd46625f43e590699a8c0f8740af173190036875c163fc9b430c72b301e",
            "9b85e75bfe129adf7e28d2ac1a8a2a186259c91e9afe5b60497f59fe48a61363",
            "cfa4592dc98b4625c70bcc5f5b39611043436e4d8818e977ae479e2321b4e731",
        ],
        [
            "f0bfc68ccc5cde3aac026b8668055c06bb286950197cf8df5b8546c2a55f8676",
            "51f046dc5d42d9a73fc12d9b3720723915f58b8b617584ae469bd081118c784d",
            "51f046dc5d42d9a73fc12d9b3720723915f58b8b617584ae469bd081118c784d",
            "0cb6b5eb789ec03c3561b6574554f1a3e9ceb265cf92e8f1edf03e445641e13a",
        ],
        [
            "3d4269b3aa052fa291db18183ebd9e05d0230faa7f474eaa28c7cebb191b552c",
            "22b0fa046129a0b3a1ddaacb7b62edd952d239aec38ea8c89bf00e15fe859547",
            "af0c7b6703225e5ff0260e2cec7c79ded10506c76f1fd86b6134b0b41481f05f",
            "932f7c251dfc76ca8fc893068ac7f76c82f311830bbc39a7d69ab1dc75adb419",
        ],
        [
            "2507de9b7116c8e38b8d9d4a9787c7ad58a5ac82c7cafca8f1f20ed13d41c07e",
            "a2a75aa84a1e31a332a49ef20767c0b4b7f2fc81784b720a6f39a666b3d28e53",
            "769d48797268911011619509485d5f68649bc56c208057de42188b7f4b6e4a40",
            "4b0946387189f8eb0d51ac2ca1156297cc69f3e7d681da2353af7b61055f6c04",
        ],
        [
            "ab675f987fa1ff564d9532b94103d382424c804e16f33278d5daf8460cafc12f",
            "d186d70dd4a861fe0b13bf5bdd43a28ffd5457128d47aee934b8efd4fa163972",
            "f3875d1c9118a39467f774837d5b73f26245add28adface6c3831d0b16311600",
            "55dc20e8bdfc4d13a6a3f1c49859f35248d1bda1d0db26efc02ccf407ec5670c",
        ],
        [
            "7f74e1ee4b024dfa1d0922f3b848891ca0bda69760a72354ee38c9a340293511",
            "1616f968954f044a8033d0639ef9eaa22658a8deb9d3bd75c4f900b8439ac053",
            "9511eb90311692dba1df5cabe16835545d8105a3a51bb1a4e2e3e77625789e59",
            "bab2454581ba3c31d61525e341c6e45dae64d63ddeb18ec7246104225d9aad27",
        ],
        [
            "38af5f517bc769ef83371332d83c438b9a15cafb94718c2d417a2b5595919325",
            "ba6d043159102150818942f0bfca69377198ce93d7df638814b4a84df74e7e3f",
            "ba6d043159102150818942f0bfca69377198ce93d7df638814b4a84df74e7e3f",
            "b3c91ba8db89652d7c93568e141479644b27fbefbb9f8ebd66697c2f3b40fc12",
        ],
        [
            "84b40c80c5c44f91e7165328f84db2507c8fd0fb58cd939705565dc60f98d4ab",
            "7cfb1e927d172cfd0fecf3616bd3077a1e485f8487f5f792a44af24602aeee78",
            "0796354388c13f2f43263a04791be6f341c0827dca22cf602e3711aeff3c270d",
            "33c419bdec3cbc5bf10811f53c8745e7832d38b0fd4f4975150989e763431702",
        ],
        [
            "fcb6c9a0acbea273445cc1c84c5fe486ba88f76ff6197e4d66732ac1b7905e0e",
            "a865fcb0d433c9205079046ddff9e3add7b3d5b85eabf77570aef6221625845a",
            "82d52b90191fa82e6125352d0df011f40d1c52c936d8472c80ab5f39be4dc275",
            "a500286f77a44da3954cd2d28bc6ceb698fe9b5f59296494cdba2223ed82781d",
        ],
        [
            "3a89d10d54534bc595f95b7266ea95a7509a13e35eaede55be49931c73e29f51",
            "9a2fd476dbc15148a72d2915223142060ebee6e8fce2a110bc00977d618f4354",
            "6d027e1197c78eeed729cdf0a08b25f6c2a36d726dcf2dc7592cbf22a64c4667",
            "26591aa301c6b90b41bb2d7d227b7513446a2281138135b606b2ccfd67073d28",
        ],
        [
            "5ad1beed45793f7e7fd2b59b1d3c64441087c31f5edbc71d5adacf3e87f3b409",
            "69947803a666ae9746282ec985bb140473bd2cca8e7e806e6b7c63dba12abf09",
            "e562faef7f4846624819ed16de66bfbc5cee8c7200d2579fa81ee00e457d0c41",
            "304f86219a3b6f8045038baa1d51271c69b4594582b05409fb08310d15893830",
        ],
        [
            "248c40bf9a05281c5c42d884c37d916c4dface070f936d293f30a1d05bce5caa",
            "ea506f676538b2aa4c60092026453ecb37a3562295be551d134cb334063aad4a",
            "27934d458e6c253b0211a6d5ffead34a7f18264c9744c8d860a5af02b486960e",
            "3fb9e265959e9ce605f662d983cf5c7606be10cf95dcf1eb96931d7d189fcd1f",
        ],
        [
            "88d60d17395bb4df69205cc2750bb2e83f8646aa56acaaeccdaec527e085bcc2",
            "ae62dc36e3f8bcc7c436cb8adb1b931af32bbe1501d048dc50d9947399f0ac0c",
            "ae62dc36e3f8bcc7c436cb8adb1b931af32bbe1501d048dc50d9947399f0ac0c",
            "1e8c4ba9a54eccd2bd9020c8333033857187eab8e17aa40f46e22acaca07d31e",
        ],
        [
            "39e952a23697e05cf624e82c36c36bb51d546ffef5aa4fc4d7b695a51cae499a",
            "8d04ce07d2251923e7c871df78ad6eb56db6c0c8b4b11864c2078f91dce17c1f",
            "94d13ad7430c8d95f9687b7f030bd22079471f02c96938fabe1d8eac13ad0e3b",
            "f33d05d0a975fcd9777db0e78a4c74ec161d90026c29dfc2bdaf79d1a24d6c0d",
        ],
        [
            "d6111d6215c5e799b92331c0e2984f25de42e9c02e37d53abad8b7cb2a9c5e9f",
            "8fb6b77c034c1b96eca447a1192e54e8efd14944595f2d8f37e0bb13b9537e59",
            "0bce86adc6fee70bb5ecb91c56afe59dd0cdf7a92bf6fa75347a48fa91bcb35c",
            "ff8143b7f3dd11e594ba558c0bc67116676376637971c03394d707a642f1fc25",
        ],
        [
            "d08d3be3602c52c45df91f7b8b16132f779e8336f88a4e6ad320874eaabf60a2",
            "04dd9e5f7311cb8ba72487effab05b8ecbd89f3c7f2e18733d2bda22a4ebd00e",
            "04dd9e5f7311cb8ba72487effab05b8ecbd89f3c7f2e18733d2bda22a4ebd00e",
            "80c34dd01d6832dbb2589120b905f302c8a7adf5b7aac0418c9c6ebb0fad4e35",
        ],
        // The following key sets have a v_in_sqrt value of 0
    ]
}

/// returns a set of private keys generated by (a fork of) the golang
/// implementation agl/ed25519 which is used by the mainstream obfs4
/// library.
///
/// All of these fail to generate a keypair capable of using elligator2
/// to encode of the public key.
///
#[cfg(feature = "elligator2")]
fn ntor_invalid_keys() -> [&'static str; 16] {
    [
        "fd0d592d67038a6253331547949d70eb7a6b6c4c4831a1bc235554765b20f845",
        "9576aa473a2b73b174e753ada7d55bc34ae8c05c1b1d6077f9a098984df9cf52",
        "5b26538e0663a453994cf49d5614926786a0549c0123fa9afc7be99e04afc9ea",
        "d4e58db7420267ad43e72e1fe0dee1acb9ca547e258e22370d76c0945f4b1a1e",
        "01b047693c6b5212607387df88d1a427d2f24bd24157058705fc090e22778a64",
        "d2d363fad3ea3aceb8262adc1184f32c6f63911e6bc008c87f366f9c2b60753c",
        "75f703e3095343cf5d3ccd05a3fea06f82509a26c391a0365a1f1ca5e1d5f82f",
        "1f6986c9146f2d4b1907a812e7e7254c82e121776d58fd9c4a5f6741a326e2ef",
        "fe8465f11b40d52dc845df0a1639398b1726409d3b52526082c3e67c52f06842",
        "4546f8e010e0d3be7ab3e97480cecc411b054013960ff4032b3d3e5afe1565e0",
        "fc0f99f041118fd44c685b87b143b48d6d8c820d9f07235eeb7f7a9468dc0ca0",
        "847c1d842a2e91521d1a63e191d3d2389e54c73378130f376d013781730ace3e",
        "7d8a740b09f477588bc9a9020b2444ee384718f889403c02f3a61e69f55e6f7f",
        "0549080985424df8f9401be8802e8c6a4c02737c474ac76c9d3f7968a3fca40a",
        "53cd411b966503129365517e5c1b04e9f52a248cc57599af9ed58c9ff5b774d4",
        "015aebbe87a5e94c5d8d3179583cf46d02af06c8f99a6d4ce8a3a4b1de097cd2",
    ]
}

const ENCODING_TESTS_COUNT: usize = 10;
struct EncodingTestCase {
    high_y: bool,
    point: &'static str,
    representative: Option<&'static str>,
}

fn encoding_testcases() -> [EncodingTestCase; ENCODING_TESTS_COUNT] {
    [
        // A not encodable point with both "high_y" values
        EncodingTestCase {
            point: "e6f66fdf6e230c603c5e6e59a254ea1476a13eb9511b9549846781e12e52230a",
            high_y: false,
            representative: None,
        },
        EncodingTestCase {
            point: "e6f66fdf6e230c603c5e6e59a254ea1476a13eb9511b9549846781e12e52230a",
            high_y: true,
            representative: None,
        },
        // An encodable point with both "high_y" values
        EncodingTestCase {
            point: "33951964003c940878063ccfd0348af42150ca16d2646f2c5856e8338377d800",
            high_y: false,
            representative: Some(
                "999b591b6697d074f266192277d554dec3c24c2ef6108101f63d94f7fff3a013",
            ),
        },
        EncodingTestCase {
            point: "33951964003c940878063ccfd0348af42150ca16d2646f2c5856e8338377d800",
            high_y: true,
            representative: Some(
                "bd3d2a7ed1c8a100a977f8d992e33aaa6f630d55089770ea469101d7fd73d13d",
                // "999b591b6697d074f266192277d554dec3c24c2ef6108101f63d94f7fff3a013",
            ),
        },
        // 0 with both "high_y" values
        EncodingTestCase {
            point: "0000000000000000000000000000000000000000000000000000000000000000",
            high_y: false,
            representative: Some(
                "0000000000000000000000000000000000000000000000000000000000000000",
            ),
        },
        EncodingTestCase {
            point: "0000000000000000000000000000000000000000000000000000000000000000",
            high_y: true,
            representative: Some(
                "0000000000000000000000000000000000000000000000000000000000000000",
            ),
        },
        // A not encodable point with both "high_y" values
        EncodingTestCase {
            point: "10745497d35c6ede6ea6b330546a6fcbf15c903a7be28ae69b1ca14e0bf09b60",
            high_y: false,
            representative: Some(
                "d660db8cf212d31ce8c6f7139e69b9ac47fd81c7c0bfcb93e364b2d424e24813",
            ),
        },
        EncodingTestCase {
            point: "10745497d35c6ede6ea6b330546a6fcbf15c903a7be28ae69b1ca14e0bf09b60",
            high_y: true,
            representative: Some(
                "489a2e0f6955e08f1ae6eb8dcdbc0f867a87a96a02d2dfd2aca21d8b536f0f1b",
            ),
        },
        // A not encodable point with both "high_y" values
        EncodingTestCase {
            point: "6d3187192afc3bcc05a497928816e3e2336dc539aa7fc296a9ee013f560db843",
            high_y: false,
            representative: Some(
                "63d0d79e7f3c279cf4a0a5c3833fd85aa1f2c004c4e466f3a3844b3c2e06e410",
            ),
        },
        EncodingTestCase {
            point: "6d3187192afc3bcc05a497928816e3e2336dc539aa7fc296a9ee013f560db843",
            high_y: true,
            representative: Some(
                "0f03b41c86aeb49acf2f76b39cc90a55a0b140b7290f1c9e032591ddcb074537",
            ),
        },
    ]
}

const DECODING_TESTS_COUNT: usize = 7;
struct DecodingTestCase {
    representative: &'static str,
    /// if we only allow least-square-root values as the representative and
    /// clear the high order two bits (effectively) ensuring that the
    /// representative value is less than `2^254 - 10`, this is the point
    /// that we should receive.
    point: &'static str,
    /// if we allow unbounded values to be used directly as representatives,
    /// not only least-square-root values, this is the point we should receive.
    non_lsr_point: &'static str,
}

fn decoding_testcases() -> [DecodingTestCase; DECODING_TESTS_COUNT] {
    [
        // A small representative with false "high_y" property
        DecodingTestCase {
            representative: "e73507d38bae63992b3f57aac48c0abc14509589288457995a2b4ca3490aa207",
            point: "1e8afffed6bf53fe271ad572473262ded8faec68e5e67ef45ebb82eeba52604f",
            non_lsr_point: "1e8afffed6bf53fe271ad572473262ded8faec68e5e67ef45ebb82eeba52604f",
        },
        // A small representative with true "high_y" property
        DecodingTestCase {
            representative: "95a16019041dbefed9832048ede11928d90365f24a38aa7aef1b97e23954101b",
            point: "794f05ba3e3a72958022468c88981e0be5782be1e1145ce2c3c6fde16ded5363",
            non_lsr_point: "794f05ba3e3a72958022468c88981e0be5782be1e1145ce2c3c6fde16ded5363",
        },
        // The last representative returning true: (p - 1) / 2
        DecodingTestCase {
            representative: "f6ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3f",
            point: "9cdb525555555555555555555555555555555555555555555555555555555555",
            non_lsr_point: "9cdb525555555555555555555555555555555555555555555555555555555555",
        },
        // The first representative returning false: (p + 1) / 2
        DecodingTestCase {
            representative: "f7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3f",
            point: "9cdb525555555555555555555555555555555555555555555555555555555555",
            non_lsr_point: "9cdb525555555555555555555555555555555555555555555555555555555555",
        },
        // 0
        DecodingTestCase {
            representative: "0000000000000000000000000000000000000000000000000000000000000000",
            point: "0000000000000000000000000000000000000000000000000000000000000000",
            non_lsr_point: "0000000000000000000000000000000000000000000000000000000000000000",
        },
        // These two tests are not least-square-root representations.

        // A large representative with false "high_y" property
        DecodingTestCase {
            representative: "179f24730ded2ce3173908ec61964653b8027e383f40346c1c9b4d2bdb1db76c",
            point: "e6e5355e0482e952cc951f13db26316ab111ae9edb58c45428a984ce7042d349",
            non_lsr_point: "10745497d35c6ede6ea6b330546a6fcbf15c903a7be28ae69b1ca14e0bf09b60",
        },
        // A large representative with true "high_y" property
        DecodingTestCase {
            representative: "8a2f286180c3d8630b5f5a3c7cc027a55e0d3ffb3b1b990c5c7bb4c3d1f91b6f",
            point: "27e222fec324b0293842a59a63b8201b0f97b1dd599ebcd478a896b7261aff3e",
            non_lsr_point: "6d3187192afc3bcc05a497928816e3e2336dc539aa7fc296a9ee013f560db843",
        },
    ]
}
